### PR TITLE
chore(deps): Isolate digest updates while keeping once a week pattern

### PR DESCRIPTION
**Pull request by drewrelmas**
# Change Summary

It is taxing to isolate the breaking change from #3235.

In this specific case, it is the `geneva` dependency: https://github.com/open-telemetry/otel-arrow/actions/runs/27225496774/job/80391437570?pr=3235

```log
error[E0063]: missing field `obo_event_map` in initializer of `geneva_uploader::GenevaClientConfig`
   --> crates/contrib-nodes/src/exporters/geneva_exporter/mod.rs:301:29
    |
301 |         let client_config = GenevaClientConfig {
    |                             ^^^^^^^^^^^^^^^^^^ missing `obo_event_map`
```

#3140 attempted to limit the number of digest PRs we get, but grouping them all together probably isn't the right move.

Instead, still get digest updates from Go and Rust once a week, but treat each one as a separate PR. That way, we can easily merge non-breaking ones and immediately have visibility into which breaking ones.

## What issue does this PR close?

N/A

## How are these changes tested?

N/A

## Are there any user-facing changes?

N/A

### Changelog

* [x] Added a `.chloggen/*.yaml` entry, OR this PR is a `chore` (indicated in title).

### CODE REVIEW

**Review by albertlockett — APPROVED** [review]
:+1:  thanks @drewrelmas
